### ISSUE TITLE
NoMethodError: undefined method `e=' for #<OpenSSL::PKey::RSA:0x.....>

### ISSUE THREAD

**Issue by mihaimuntenas** [jooeycheng/adyen-cse-ruby#4]
The `NoMethodError` is triggered from 
https://github.com/jooeycheng/adyen-cse-ruby/blob/v1.0.0/lib/adyen_cse/encrypter.rb#L49
https://github.com/jooeycheng/adyen-cse-ruby/blob/master/lib/adyen_cse/encrypter.rb#L49

as in MRI 2.4.3 the OpenSSL::PKey::RSA class changed; you are suppose to call #set_keys.
https://ruby-doc.org/stdlib-2.4.3/libdoc/openssl/rdoc/OpenSSL/PKey/RSA.html#method-i-set_key

Please check the following commit in the fork of @vbanthia, maybe he could make a PR (instead of publishing the gem himself with v2.0.0).
https://github.com/vbanthia/adyen-cse-ruby/commit/898d2755203533c8e216eb55da3c132c09e67894

Ruby Version: ruby 2.4.4p296 (2018-03-28 revision 63013)

**Comment by jooeycheng** [comment]
Hi @mihaimuntenas. Thanks for reporting this issue. 
Sorry, I've previously unwatched this repo 🤦‍♂️, so i did not notice this issue was posted. 

Thanks @surzycki for the PR! Reviewing 🔍

**Comment by jooeycheng** [comment]
@mihaimuntenas please update to `1.1.0`. Thanks 🙏

**Comment by mihaimuntenas** [comment]
@jooeycheng will do thanks! But please keep following this repo ...

**Comment by jooeycheng** [comment]
@mihaimuntenas yep, i'm now watching this repo!

**Comment by toshakamath** [comment]
I keep getting the same error for version ruby 2.7 as well

**Comment by jooeycheng** [comment]
Hi @toshakamath, can you provide more info?

The [latest build on Ruby 2.7.1 passed](https://travis-ci.org/github/jooeycheng/adyen-cse-ruby/jobs/701203432).
Can you double check the gem version, and Ruby version?
